### ISSUE TITLE
Getting DPDK to work with LKL

### ISSUE THREAD

**Issue by mithunrn** [lkl/linux#449]
We are trying to get LKL working with DPDK. 
Set this up as per  https://github.com/lkl/linux/wiki/Howto:-DPDK-with-LKL

Ran into this crash which I was able to get past using the attached patch where I reorder dpdk_netdev creation in the init code.

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb51c1a3dd4 in __cpu_try_get_lock (n=0) at arch/lkl/kernel/cpu.c:63
63              lkl_ops->mutex_lock(cpu.lock);
(gdb) bt
#0  0x00007fb51c1a3dd4 in __cpu_try_get_lock (n=0) at arch/lkl/kernel/cpu.c:63
#1  0x00007fb51c1a3f75 in lkl_cpu_get () at arch/lkl/kernel/cpu.c:99

Has anyone run into similar issues with DPDK and LKL ?
When I have my application opening multiple socket descriptors, I see LKL sub-system runs out of descriptors soon. I did try to "sysctl":"fs.file-max=2048000" in my config json and trying the LKL_FDSET in the code. 
Has anyone ran into descriptor resource problem as these ?
How has been the experience with DPDK and LKL ?

Appreciate any help

[dpdk_lkl.txt](https://github.com/lkl/linux/files/2259059/dpdk_lkl.txt)

**Comment by mithunrn** [comment]
Appreciate any help. We are interested in knowing any efforts to get DPDK working with LKL.

$ uname -a
Linux ubuntu1404 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
