### ISSUE TITLE
in ubuntu  run tests have issues. it say i hadn"t installed yamlish, but I do,it still error

### ISSUE THREAD

**Issue by 118988577** [lkl/linux#493]
./tests/run.py
Traceback (most recent call last):
     File "./tests/run.py", line 16, in <module>
           import tap13
     File "/home/zw01/桌面/linux-master/tools/lkl/tests/tap13.py", line 18,in <module>
           import yamlish
import Eror: No module name yamlish
make:***[Makefile:123:run-tests] error 1

**Comment by 118988577** [comment]
I had knew,because of python versions
